apiVersion: apps/v1
kind: Deployment
metadata:
  name: valhalla
  namespace: valhalla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: valhalla-app
  template:
    metadata:
      labels:
        app: valhalla-app
    spec:
      containers:
      - name: valhalla
        image: 853845817090.dkr.ecr.ap-south-1.amazonaws.com/valhalla:latest
        resources:
          limits:
            cpu: "200m"   # Set a limit of 200 milliCPU (0.2 cores)
            memory: "256Mi"  # Set a limit of 256 megabytes
          requests:
            cpu: "100m"   # Request 100 milliCPU (0.1 cores)
            memory: "128Mi"  # Request 128 megabytes
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: valhalla
  namespace: valhalla
spec:
  selector:
    app: valhalla-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use 'LoadBalancer' if you want to expose the service externally

